export interface Competitor {
  name: string;
  slug: string;
  tagline: string;
  freeplan: string;
  paidPrice: string;
  features: { name: string; them: boolean | string; us: boolean | string }[];
  weaknesses: string[];
  ourAdvantages: string[];
}

export const competitors: Record<string, Competitor> = {
  calendly: {
    name: "Calendly",
    slug: "calendly",
    tagline: "The most popular scheduling tool — but is it worth the price?",
    freeplan: "1 event type, no integrations",
    paidPrice: "$10/mo (Standard), $16/mo (Teams)",
    features: [
      { name: "Free event types", them: "1", us: "3" },
      { name: "AI chat scheduling", them: false, us: true },
      { name: "MCP for AI agents", them: false, us: true },
      { name: "Google Calendar sync", them: true, us: true },
      { name: "Google Meet auto-create", them: true, us: true },
      { name: "Custom booking questions", them: "Paid only", us: true },
      { name: "Team scheduling", them: "Paid only", us: true },
      { name: "Meeting polls", them: "Paid only", us: true },
      { name: "Workflows & automations", them: "Paid only", us: true },
      { name: "Booking page customization", them: "Limited free", us: true },
      { name: "Remove branding", them: "$16/mo", us: "$1/mo" },
      { name: "Crypto payments", them: false, us: true },
    ],
    weaknesses: [
      "Free plan is extremely limited (1 event type)",
      "Costs $10-16/month for features that should be free",
      "No AI capabilities whatsoever",
      "No MCP integration for AI agents",
      "Removing branding costs $16/month",
    ],
    ourAdvantages: [
      "3 free event types (3x more than Calendly)",
      "AI chat scheduling built in — no add-ons needed",
      "MCP ready — any AI agent can manage your calendar",
      "Pro plan is $1/mo — 90% cheaper than Calendly",
      "Remove branding for $1/mo vs Calendly's $16/mo",
    ],
  },
  "cal-com": {
    name: "Cal.com",
    slug: "cal-com",
    tagline: "Open-source scheduling — but self-hosting isn't free.",
    freeplan: "Self-hosted only (requires technical setup)",
    paidPrice: "$12/mo (Cloud)",
    features: [
      { name: "Free hosted plan", them: false, us: true },
      { name: "AI chat scheduling", them: false, us: true },
      { name: "MCP for AI agents", them: false, us: true },
      { name: "Google Calendar sync", them: true, us: true },
      { name: "Self-hosting option", them: true, us: false },
      { name: "Team scheduling", them: true, us: true },
      { name: "Custom booking questions", them: true, us: true },
      { name: "Workflows", them: true, us: true },
      { name: "Meeting polls", them: true, us: true },
      { name: "No technical setup needed", them: false, us: true },
      { name: "Crypto payments", them: false, us: true },
    ],
    weaknesses: [
      "No free hosted plan — must self-host or pay $12/mo",
      "Self-hosting requires DevOps knowledge, server costs",
      "No AI features",
      "Complex setup compared to hosted alternatives",
    ],
    ourAdvantages: [
      "Free hosted plan — no server needed",
      "AI chat and MCP built in",
      "Zero setup — sign up and start scheduling",
      "Pro plan $1/mo vs Cal.com $12/mo",
    ],
  },
  tidycal: {
    name: "TidyCal",
    slug: "tidycal",
    tagline: "Cheap lifetime deal — but limited features.",
    freeplan: "Limited free tier",
    paidPrice: "$29 lifetime",
    features: [
      { name: "Lifetime pricing", them: true, us: false },
      { name: "AI chat scheduling", them: false, us: true },
      { name: "MCP for AI agents", them: false, us: true },
      { name: "Google Calendar sync", them: true, us: true },
      { name: "Team scheduling", them: false, us: true },
      { name: "Workflows & automations", them: false, us: true },
      { name: "Meeting polls", them: false, us: true },
      { name: "Custom booking questions", them: "Limited", us: true },
      { name: "Routing forms", them: false, us: true },
      { name: "Crypto payments", them: false, us: true },
    ],
    weaknesses: [
      "Very limited feature set compared to full platforms",
      "No team scheduling or round-robin",
      "No workflow automations",
      "No AI features",
      "Development pace is slow",
    ],
    ourAdvantages: [
      "Full-featured platform, not a bare-bones tool",
      "AI chat and MCP integration",
      "Team scheduling, workflows, routing forms",
      "$1/mo Pro — pays for itself vs lifetime lock-in",
    ],
  },
  acuity: {
    name: "Acuity Scheduling",
    slug: "acuity",
    tagline: "Part of Squarespace — powerful but pricey with no free tier.",
    freeplan: "No free tier (7-day trial only)",
    paidPrice: "$16/mo (Emerging), $27/mo (Growing)",
    features: [
      { name: "Free plan", them: false, us: true },
      { name: "AI chat scheduling", them: false, us: true },
      { name: "MCP for AI agents", them: false, us: true },
      { name: "Google Calendar sync", them: true, us: true },
      { name: "Payment collection", them: true, us: true },
      { name: "Custom intake forms", them: true, us: true },
      { name: "Team scheduling", them: "$27/mo", us: true },
      { name: "Workflows", them: true, us: true },
      { name: "Crypto payments", them: false, us: true },
      { name: "Meeting polls", them: false, us: true },
    ],
    weaknesses: [
      "No free tier at all — starts at $16/mo",
      "Part of Squarespace ecosystem (vendor lock-in)",
      "No AI capabilities",
      "Team features locked behind $27/mo plan",
    ],
    ourAdvantages: [
      "Generous free plan with 3 event types",
      "AI chat and MCP built in",
      "Pro is $1/mo — 94% cheaper",
      "Independent platform, no ecosystem lock-in",
    ],
  },
  doodle: {
    name: "Doodle",
    slug: "doodle",
    tagline: "Great for polls — but the free plan is full of ads.",
    freeplan: "Ad-supported, limited polls",
    paidPrice: "$6.95/mo (Pro)",
    features: [
      { name: "Free plan", them: "Ad-supported", us: "Ad-free" },
      { name: "AI chat scheduling", them: false, us: true },
      { name: "MCP for AI agents", them: false, us: true },
      { name: "Meeting polls", them: true, us: true },
      { name: "Booking pages", them: "Paid only", us: true },
      { name: "Google Calendar sync", them: true, us: true },
      { name: "Custom branding", them: "Paid only", us: "$1/mo" },
      { name: "Team scheduling", them: "Paid only", us: true },
      { name: "Workflows", them: false, us: true },
      { name: "Crypto payments", them: false, us: true },
    ],
    weaknesses: [
      "Free plan is cluttered with ads",
      "Primarily a polling tool, not a full scheduling platform",
      "No AI features",
      "Booking pages are paid-only",
    ],
    ourAdvantages: [
      "Clean, ad-free free plan",
      "Full scheduling platform + polls",
      "AI chat and MCP integration",
      "More features in free than Doodle's paid plan",
    ],
  },
};
